# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3  # Ensure this fetches your repository correctly
    - name: Build
      run: swift build -v  # Replace with your build command



name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_project:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          xcodebuild -workspace UnitTestGithub/UnitTestGithub.xcworkspace -scheme UnitTestGithubTests -destination 'platform=iOS Simulator,name=iPhone 15' test -allowProvisioningUpdates
