# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS SDK CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create and boot iOS Simulator
      run: |
        SIMULATOR_NAME="TestSim"
        RUNTIME="com.apple.CoreSimulator.SimRuntime.iOS-17-0" # Replace with a valid runtime
        SIMULATOR_ID=$(xcrun simctl create $SIMULATOR_NAME com.apple.CoreSimulator.SimDeviceType.iPhone-12 $RUNTIME)
        xcrun simctl boot $SIMULATOR_ID
        echo "Sim ID: $SIMULATOR_ID"

    - name: Build and test
      run: |
        SIMULATOR_ID=$(xcrun simctl list devices | grep "TestSim" | grep -o -E '\([0-9A-F-]+\)' | tr -d '()')
        xcodebuild clean test -project UnitTestGithub.xcodeproj -scheme UnitTestGithub -sdk iphonesimulator -destination "id=$SIMULATOR_ID" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

    - name: Shutdown iOS Simulator
      run: |
        SIMULATOR_ID=$(xcrun simctl list devices | grep "TestSim" | grep -o -E '\([0-9A-F-]+\)' | tr -d '()')
        xcrun simctl shutdown $SIMULATOR_ID
        xcrun simctl delete $SIMULATOR_ID
